name: Deployment
run-name: Deploying for ${{ github.ref }}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "TEST=ASDF" >> $GITHUB_ENV
    - run: echo $GITHUB_ENV
    - run: echo ${{ env.TEST }}
    - run: cat $GITHUB_ENV